import type { Metadata } from "next";

import './globals.css'
import { Inter } from 'next/font/google'
import { SiteHeader } from '@/components/site-header'
import { SiteFooter } from '@/components/site-footer'
import { LanguageProvider } from '@/contexts/language-context'
import { Toaster } from "@/components/ui/toaster"

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: "FEFVEN",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="h-full">
      <body className={`${inter.className} flex flex-col min-h-screen`}>
          <LanguageProvider>
            <SiteHeader />
            <main className="flex-grow">{children}</main>
            <SiteFooter />
            <Toaster />
          </LanguageProvider>
      </body>
    </html>
  )
}

